services:
  backend:
    build:
      context: ./backend/bait-api
      dockerfile: Dockerfile
    container_name: bait-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend/bait-api:/var/www
      - /var/www/vendor         
      - /var/www/bootstrap/cache
    ports:
      - "8001:8000"
    depends_on:
      - mysql
      - mysql_test
      - redis
    command: php artisan serve --host=0.0.0.0 --port=8000
      
  mysql:
    image: mysql:8.0
    container_name: bait-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile 
    container_name: bait-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["ng", "serve", "--host", "0.0.0.0", "--poll=2000"]

  redis:
    image: redis:alpine
    container_name: bait-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  mysql_test:
    image: mysql:8.0
    container_name: bait-mysql-test
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE_TEST}
      MYSQL_USER: ${DB_USERNAME_TEST}
      MYSQL_PASSWORD: ${DB_PASSWORD_TEST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD_TEST}
    ports:
      - "3317:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: bait-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./backend/bait-api/public:/var/www/public:ro
    depends_on:
      - frontend
      - backend

  reverb:
    build:
      context: ./backend/bait-api
      dockerfile: Dockerfile
    container_name: bait-reverb
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8081:8080"
    volumes:
      - ./backend/bait-api:/var/www
      - /var/www/vendor         
      - /var/www/bootstrap/cache
    depends_on:
      - redis 
    env_file:
      - .env
    command: /bin/sh -c "php artisan config:clear && sleep 10 && php artisan reverb:start --host=0.0.0.0 --port=8080"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bait-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
      
# To add later: vistualization for de db
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin

volumes:
  mysql_data:
  mysql_test_data:
  redis_data:

